version: '3.5'

volumes:
  postgres_data:
    driver: local
  # neo4j_data:
  #   driver: local
  keycloak_data:
    driver: local
  meveo_data:
    driver: local
  meveo_binary_data:
    driver: local

services:
  postgres:
    image: postgres:9.5.21
    container_name: postgres
    networks:
      - meveo
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: meveo
      POSTGRES_USER: meveo
      POSTGRES_PASSWORD: meveo
    ports:
      - 5432:5432
  # neo4j:
  #   image: manaty/neo4j-meveo:3.5.13
  #   container_name: neo4j
  #   build:
  #     context: ./
  #     dockerfile: ../Dockerfile.neo4j
  #   networks:
  #     - meveo
  #   restart: unless-stopped
  #   volumes:
  #     - neo4j_data:/data
  #   environment:
  #     NEO4J_AUTH: neo4j/neo4j123
  #   ports:
  #     - 7474:7474
  #     - 7687:7687
  keycloak:
    image: manaty/keycloak
    container_name: keycloak
    networks:
      - meveo
    restart: unless-stopped
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data/keycloakdb
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8081:8080
  meveo:
    image: manaty/wildfly-meveo:dev-latest
    container_name: meveo
    networks:
      - meveo
    volumes:
      - meveo_data:/opt/jboss/wildfly/meveodata
      - meveo_binary_data:/tmp/meveo/binary/storage
    environment:
      WILDFLY_LOG_CONSOLE_LEVEL: "INFO"    # default: OFF
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - keycloak

networks:
  meveo:
    name: meveo
