version: '3.5'

volumes:
  postgres_data:
    driver: local
  # neo4j_data:
  #   driver: local
  keycloak_data:
    driver: local
  meveo_data:
    driver: local
  meveo_binary_data:
    driver: local

services:
  postgres:
      image: postgres:9.5.21
      container_name: postgres
      networks:
        - meveo
      restart: unless-stopped
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: meveo
        POSTGRES_USER: meveo
        POSTGRES_PASSWORD: meveo
      ports:
        - 5432:5432
  # neo4j:
  #     image: manaty/neo4j-meveo:dev-latest
  #     container_name: neo4j
  #     networks:
  #       - meveo
  #     restart: unless-stopped
  #     volumes:
  #       - neo4j_data:/data
  #     environment:
  #       NEO4J_AUTH: neo4j/neo4j123
  #     ports:
  #       - 7474:7474
  #       - 7687:7687
  keycloak:
      image: manaty/keycloak
      container_name: keycloak
      networks:
        - meveo
      restart: unless-stopped
      volumes:
        - keycloak_data:/opt/jboss/keycloak/standalone/data/keycloakdb
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 8081:8080
  meveo:
      build: 
        context: ../docker/
        dockerfile: Dockerfile.dev
      container_name: meveo
      networks:
        - meveo
      volumes:
        #- meveo_data:/opt/jboss/wildfly/meveodata
        - ..:/opt/jboss/wildfly/meveodata/default/git/meveo-src
        - meveo_binary_data:/tmp/meveo/binary/storage
      environment:
        KEYCLOAK_URL: http://localhost:8081/auth   # For Linux localhost system
        #KEYCLOAK_URL: http://host.docker.internal:8081/auth   # For Windows & MacOS localhost system
        WILDFLY_DEBUG_ENABLE: "true"
        WILDFLY_DEBUG_PORT: 8787
      ports:
        - 8080:8080
        - 8787:8787
        - 9990:9990
      depends_on:
        - postgres

networks:
  meveo:
    name: meveo